#!/usr/bin/env python3
import json
from pathlib import Path
strings={
'Library':'图库','Transfers':'传输','Account':'我的','Photo':'照片','Video':'视频','Photos':'照片','Videos':'视频',
'Sign in':'登录','Sign out':'退出登录','Email':'邮箱','Password':'密码','New password':'新密码','Current password':'当前密码',
'Create an account':'注册账号','Create account':'注册','Forgot password?':'忘记密码？','Back to sign in':'返回登录',
'Nickname':'昵称','Given name':'名字','Family name':'姓氏','Gender':'性别','Prefer not to say / Other':'不愿透露／其他','Female':'女','Male':'男',
'Verification code':'验证码','Verify your email':'验证邮箱','Verify email':'验证邮箱','Send a new code':'重新发送验证码',
'Reset password':'重设密码','Set a new password':'设置新密码','Send reset code':'发送重设验证码','Save new password':'保存新密码',
'Your photos and videos, together.':'把照片与视频，收藏在一起。',
'Use at least 8 characters with uppercase, lowercase, a number and a symbol.':'密码至少 8 位，包含大写字母、小写字母、数字和符号。',
'I agree to the terms and have read the privacy notice.':'我同意服务条款，并已阅读隐私说明。',
'Terms of use':'服务条款','Privacy notice':'隐私说明','Done':'完成','Try again':'重试',
'Load terms and privacy notice':'加载服务条款和隐私说明',
'Invited beta · Keep an independent copy of important originals.':'受邀测试版 · 请为重要原件保留独立备份。',
'Enter the code sent to your email.':'请输入发送到你邮箱的验证码。','Email verified. You can now sign in.':'邮箱验证成功，现在可以登录。',
'Password updated. Sign in with your new password.':'密码已更新，请使用新密码登录。','A new code has been sent.':'新验证码已发送。',
'Before you continue':'继续之前','Please review the current terms and privacy notice for your PinHaoYun account.':'请阅读适用于你的 PinHaoYun 账号的最新服务条款与隐私说明。',
'Agree and continue':'同意并继续','Your account':'你的账号',
'Your library starts here':'从这里开始收藏','Add photos, videos and Live Photos. Your originals stay on your device.':'添加照片、视频和实况照片。手机里的原件会保留。',
'Add photos and videos':'添加照片和视频','Filter library':'筛选图库','Media type':'媒体类型','All media':'全部媒体','Load more':'加载更多','Date unknown':'日期未知',
'Open Live Photo':'查看实况照片','Open media':'查看媒体','No transfers yet':'还没有传输任务',
'Add photos and videos from your library. Uploads and retries appear here.':'从图库添加照片和视频，在这里查看上传进度与重试。',
'Uploading':'上传中','Finishing':'即将完成','Completed':'已完成','Needs attention':'需要处理','Cancelled':'已取消','Waiting':'等待中',
'Retry':'重试','Cancel upload':'取消上传','Upload progress':'上传进度',
'Background transfers resume when iOS allows. Reopen the app after force quitting.':'后台传输会在 iOS 允许时继续；强制关闭 App 后，请重新打开以恢复。',
'Loading original':'正在加载原件','Unable to load media':'暂时无法加载','Try refreshing this item.':'请刷新此项目后重试。','Refresh access':'刷新访问链接',
'Save original to Photos':'保存原件到相册','Save to Files or share':'存储到文件或分享','Media details':'媒体详情',
'Delete cloud copy':'删除云端副本','Delete this cloud copy?':'删除这个云端副本？',
'This removes the cloud original and thumbnail. Photos on your device are kept.':'此操作将删除云端原件和缩略图，手机相册不受影响。',
'Live Photo. Touch and hold to play.':'实况照片，长按播放。',
'Allow Photos access in Settings, or use Save to Files.':'请在系统设置中允许相册访问，或选择“存储到文件”。','Original saved to Photos.':'原件已保存到相册。',
'File name':'文件名','Date':'日期','Size':'大小','Resolution':'分辨率','Device':'拍摄设备','Location':'位置',
'Storage':'存储空间','Storage used':'已用存储空间','Plan':'当前方案','Privacy and account':'隐私与账号',
'Delete account':'注销账号','Delete your PinHaoYun account?':'注销你的 PinHaoYun 账号？',
'This deletes the account shared by Web and iOS. Access stops immediately and cloud photos, videos and account data will be deleted within 30 days.':'注销作用于 Web 与 iOS 共用账号。访问会立即停止，云端照片、视频和账号资料将在 30 天内删除。',
'Photos on your device are kept. Download any cloud originals you need before continuing.':'手机相册会保留。继续之前，请先下载你需要的云端原件。',
'Confirm your identity':'验证身份','Delete account and cloud data':'注销账号并删除云端资料','Permanently delete your account?':'永久注销账号？',
'Confirm account deletion':'确认注销账号','There is no recovery promise after deletion begins.':'删除开始后，不提供恢复承诺。',
'Account deleted':'账号已删除','Account deletion requested':'已提交注销申请','Account deletion':'账号注销',
'Cloud data will be deleted within 30 days. Photos on your device are kept.':'云端资料将在 30 天内删除，手机相册不受影响。',
'Delete by':'最迟删除时间','Check deletion status':'查看注销进度','Return to sign in':'返回登录',
'Each original must be smaller than 2 GB.':'每个原始文件不得超过 2 GB。','This original format is not supported yet.':'暂不支持这种原始文件格式。',
'The local original is unavailable. Add this item again.':'本地原件暂时不可用，请重新添加此项目。',
'Connection interrupted. Check your connection, then retry.':'连接已中断，请检查网络后重试。',
'Secure storage is unavailable. Unlock your device and try again.':'安全存储暂时不可用，请解锁设备后重试。',
'Verify your email before signing in.':'请先验证邮箱再登录。',
'Your email or password is incorrect, or your session has expired.':'邮箱或密码不正确，或登录状态已过期。',
'The code is incorrect or has expired. Request a new one.':'验证码不正确或已过期，请重新获取。',
'This email already has an account. Sign in instead.':'这个邮箱已经注册，请直接登录。',
'The service is temporarily unavailable. Please try again later.':'服务暂时无法连接，请稍后重试。','Please sign in again.':'请重新登录。',
'The request failed. Please try again.':'操作未完成，请重试。',
'Loading your account':'正在加载账号',
'Loading terms and privacy notice':'正在加载服务条款与隐私政策',
'Check account deletion':'查询账号注销进度',
'Sign out and cancel unfinished uploads?':'退出登录并取消未完成的上传？',
'Cancel uploads and sign out':'取消上传并退出登录',
'Unfinished uploads will be cancelled. Add them again after signing in. Photos on your device, completed cloud files and transfer history are kept.':'未完成的上传将取消，重新登录后需要再次添加。手机相册、已完成的云端文件及传输记录会保留。',
'Waiting for network':'等待网络',
'Checking deletion request':'正在确认注销申请',
'%@ of %@ used':'已用 %@，共 %@',
'Free':'免费版',
'PinHaoYun · Beta 0.1\nYour device\'s Photos library is never removed by account deletion.':'PinHaoYun · 测试版 0.1\n注销账号不会删除手机相册。'
}
strings.update({'Account details': '账号信息',
 'Your details': '个人信息',
 'New password and code': '新密码与验证码',
 'Your agreement': '条款确认',
 'A verification code was sent to': '验证码已发送至',
 'Use a different email': '使用其他邮箱',
 'Enter a valid email address.': '请输入有效的邮箱地址。',
 'Your password does not meet the requirements below.': '密码尚未满足下方要求。',
 'Enter the 6-digit code from your email.': '请输入邮件中的 6 位验证码。',
 'These fields are required by your PinHaoYun account. You can choose not to disclose your gender.': '以下为 '
                                                                                                     'PinHaoYun '
                                                                                                     '账号必填资料，性别可以选择不愿透露。',
 'Reload terms and privacy notice': '重新加载服务条款与隐私说明',
 'Resend available in %lld seconds.': '%lld 秒后可重新发送。',
 'Email or password is incorrect.': '邮箱或密码不正确。',
 'Privacy': '隐私',
 'Testing draft': '测试草案',
 'Version: %@': '版本：%@',
 'Review terms': '阅读并确认条款',
 'Retry agreement submission': '重新提交条款确认',
 'Your cloud account data has been deleted. Photos on your device are kept.': '云端账号资料已删除，手机相册会保留。',
 'Last checked': '上次查询时间',
 'Preparing uploads': '正在准备上传',
 'Stopping preparation': '正在停止准备',
 'Originals prepared': '已准备的原件',
 '%lld of %lld originals prepared': '已准备 %lld / %lld 个原件',
 'Keep the app open while originals are prepared. Items already in Transfers can continue uploading.': '准备原件时请保持 '
                                                                                                       'App '
                                                                                                       '打开。已加入传输队列的项目可以继续上传。',
 'Stop preparing': '停止准备',
 '%lld items added to Transfers': '已将 %lld 个项目加入传输队列',
 'Preparation stopped. Your Photos library is unchanged.': '准备已停止，手机相册不受影响。',
 '%lld items could not be prepared. Choose them again to retry.': '%lld 个项目未能准备完成，请重新选择以重试。',
 'View transfers': '查看传输',
 'Dismiss': '关闭提示',
 'Go to library': '前往图库',
 'In progress': '进行中',
 'History': '传输历史',
 'About background uploads': '关于后台上传',
 '%@ of %@': '%@ / %@',
 'No videos match this filter': '此筛选下没有视频',
 'No photos match this filter': '此筛选下没有照片',
 'Change the filter to see other media in your library.': '调整筛选即可查看图库中的其他媒体。',
 'Show all media': '显示全部媒体',
 'Live Photo': '实况照片',
 'Play Live Photo': '播放实况照片',
 'Touch and hold to play': '长按可播放',
 'Try loading this original again.': '请尝试重新加载此原件。',
 'Try loading again': '重新加载',
 'Saving original to Photos': '正在保存原件到相册',
 'Preparing files to share': '正在准备分享文件',
 'Deleting cloud copy': '正在删除云端副本',
 'Retry saving to Photos': '重新保存到相册',
 'Retry preparing files': '重新准备文件',
 'Retry cloud deletion': '重试删除云端副本',
 'Open Settings': '打开系统设置',
 'Video playback failed. Try loading it again.': '视频未能播放，请重新加载。',
 'Swipe up or down to zoom.': '向上或向下轻扫可缩放。',
 'Reset zoom': '还原缩放',
 '%lld percent zoom': '缩放至百分之 %lld',
 'Copy file name': '复制文件名'})

strings.update({
'Automatic backup':'自动备份','Automatic backup is off':'自动备份已关闭',
'Backup content':'备份内容','Photos to back up':'备份范围','Only new photos':'仅新增照片','All accessible photos':'全部可访问照片',
'Include videos':'包含视频','Network':'网络','Allow cellular data':'允许蜂窝网络',
'Backup time':'备份时间','Use a daily time window':'设置每日备份时段','Start':'开始时间','End':'结束时间',
'Choose different start and end times.':'开始和结束时间不能相同。',
'Uses your current local time, including travel and daylight saving. Started items may finish after the window ends.':'跟随手机当地时间，包含旅行换时区及夏令时。已开始的项目可能在时段结束后完成。',
'Photos access':'相册权限','Only your selected photos are accessible.':'只能访问你授权选择的照片。','Photos access is available.':'已获得相册访问权限。',
'Manage selected photos':'管理已授权照片','Check for new photos':'检查新增照片','Retry backup issues':'重试未完成的备份',
'Preparing automatic backup':'正在准备自动备份','Backup issues':'备份问题','Skipped':'已跳过','Paused':'已暂停','Retrying later':'稍后重试',
'Enable automatic backup?':'开启自动备份？','Enable backup':'开启备份','Include existing photos?':'包含现有照片？','Back up existing photos':'备份现有照片',
'All accessible photos will be considered for backup. This may use significant cloud storage and network data.':'将检查全部可访问照片并加入备份，可能占用较多云端空间和网络流量。',
'Only photos newly accessible after activation will be backed up, including older photos you import later. Your current photos are kept on this device.':'仅备份开启后新增或新授权的照片，也包括之后导入的旧照片。当前照片会保留在手机上。',
'This device backs up to the signed-in account. Deleting from Photos does not delete cloud copies.':'本机备份至当前登录账号，删除手机照片不会删除云端副本。',
'Live Photos always include their motion. Hidden photos and unsupported originals are skipped.':'实况照片始终包含动态资源。隐藏照片和暂不支持的原件会跳过。',
'Originals may use Wi-Fi and cellular data, including downloads from iCloud.':'原件可以通过 Wi-Fi 或蜂窝网络传输，也包括从 iCloud 下载。',
'Originals wait for Wi-Fi, including downloads from iCloud.':'原件仅通过 Wi-Fi 传输，也包括从 iCloud 下载。',
'iOS decides when background work runs. Exact start times are not guaranteed. Reopen the app after force quitting to resume backup.':'后台运行时机由 iOS 决定，无法保证准点启动。强制关闭 App 后，请重新打开以恢复备份。',
'Deleted cloud copies are not automatically uploaded again. Select an original manually if you want to upload it again.':'云端主动删除的项目不会自动回传。如需重新上传，请手动选择原件。',
'Deleted cloud copy will not be backed up again. Choose it manually to upload again.':'云端副本已删除，不会自动再次备份；可手动选择原件重新上传。',
'%lld backed up · %lld pending · %lld need attention':'已备份 %lld 项 · 待处理 %lld 项 · 需处理 %lld 项',
'Checking your Photos library':'正在检查手机相册','Some originals need attention':'部分原件需要处理','Backing up your originals':'正在备份原件','Backup is up to date':'备份已更新',
'Review terms before backup':'请先确认条款再继续备份','Allow Photos access to resume backup':'允许相册访问后可恢复备份',
'Waiting for Wi-Fi':'等待 Wi-Fi','Waiting for Low Data Mode to end':'等待关闭低数据模式','Waiting for Low Power Mode to end':'等待关闭低电量模式',
'Waiting for your backup time window':'等待指定备份时段','Outside the selected backup scope':'不在当前选择的备份范围内','Video backup is off':'视频备份已关闭',
'Updating backup settings':'正在更新备份设置',
'Finishing started backups':'正在完成已开始的备份',
'Not enough device storage. Free some space, then retry backup.':'手机可用空间不足，请释放空间后重试备份。',
'This original is no longer accessible in Photos.':'已无法从手机相册访问这个原件。','The Live Photo motion resource is unavailable.':'暂时无法获取这张实况照片的动态资源。',
'Beta diagnostics':'测试版诊断','Export backup diagnostics':'导出备份诊断',
'Includes device type, times, network state and backup counts. No photos or login credentials.':'包含设备类型、时间、网络状态和备份数量，不含照片或登录凭据。',
'Cloud storage is full. Free some cloud space, then retry.':'云端空间不足，请释放云端空间后重试。','Too many requests. Please wait and try again.':'操作过于频繁，请稍后重试。'
})
strings.update({"PinHaoYun · Beta 0.2\nThis beta uses separate test accounts and cloud files.\nYour device's Photos library is never removed by account deletion.": 'PinHaoYun · 测试版 0.2\n本测试版使用独立的测试账号和云端图库。\n注销账号不会删除手机相册。', 'This removes the cloud original and thumbnail. Photos on your device are kept. Automatic backup will not upload this copy again; you can upload it manually.': '删除云端原件和缩略图，手机相册会保留。自动备份不会再次上传此副本；如需恢复，可手动上传。'})
strings.update({'New camera photos need to be added to your selection, or you can allow full Photos access in Settings.': '新拍照片需要追加授权，也可以在系统设置中允许访问全部照片。', 'Allow access to this photo to resume its backup, or cancel this transfer.': '允许访问这张照片后可恢复备份，或取消此传输任务。', 'Another transfer is updating this item. Try again shortly.': '另一项传输正在处理相同原件，请稍后重试。', "This deletes this beta's isolated test account. Production Web accounts are separate. Access stops immediately and cloud photos, videos and account data will be deleted within 30 days.": '此操作注销本测试版的隔离测试账号，生产 Web 账号与其独立。登录和上传会立即停止，云端照片、视频及账号资料将在 30 天内删除。'})
strings.update({'Enter reset code': '输入重设验证码', 'Continue': '继续', 'Confirm new password': '再次输入新密码', 'The passwords do not match.': '两次输入的密码不一致。', 'Enter your new password twice.': '输入并确认新密码'})
output={'sourceLanguage':'en','strings':{en:{'localizations':{'zh-Hans':{'stringUnit':{'state':'translated','value':zh}}}} for en,zh in strings.items()},'version':'1.0'}
root=Path(__file__).resolve().parents[1]
(root/'App/Resources/Localizable.xcstrings').write_text(json.dumps(output,ensure_ascii=False,indent=2)+'\n')
for lang,photo,add in [('en','Choose originals to upload, or enable optional backup of the photos and videos you authorize, including Live Photos and iCloud originals.','Save your cloud originals and Live Photos to your device\'s Photos library.'),('zh-Hans','选择原件上传，或主动开启自动备份，访问你授权的照片、视频、实况照片及 iCloud 原件。','将云端照片、视频和实况照片原件保存到手机相册。')]:
 folder=root/f'App/Resources/{lang}.lproj';folder.mkdir(parents=True,exist_ok=True)
 (folder/'InfoPlist.strings').write_text('"NSPhotoLibraryUsageDescription" = '+json.dumps(photo,ensure_ascii=False)+';\n"NSPhotoLibraryAddUsageDescription" = '+json.dumps(add,ensure_ascii=False)+';\n')
print(f'Wrote {len(strings)} Simplified Chinese translations.')
